// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxIw89Qv5XFNPfH09sprQ4xJ6uF2P5Ok0',
    appId: '1:345031892052:web:ccdf11e47b739049a561c1',
    messagingSenderId: '345031892052',
    projectId: 'social-sphere-c2d28',
    authDomain: 'social-sphere-c2d28.firebaseapp.com',
    storageBucket: 'social-sphere-c2d28.appspot.com',
    measurementId: 'G-3Q513ZJN3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPVQ0nJHeEJP_6gR8JKDIl00ab6JR7ZCA',
    appId: '1:345031892052:android:fb7a4826796cee47a561c1',
    messagingSenderId: '345031892052',
    projectId: 'social-sphere-c2d28',
    storageBucket: 'social-sphere-c2d28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEokwDuy5zO3iahtR0fudmwIrUBLoaVS0',
    appId: '1:345031892052:ios:eb40b89a720bbed3a561c1',
    messagingSenderId: '345031892052',
    projectId: 'social-sphere-c2d28',
    storageBucket: 'social-sphere-c2d28.appspot.com',
    iosBundleId: 'com.example.socialSphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEokwDuy5zO3iahtR0fudmwIrUBLoaVS0',
    appId: '1:345031892052:ios:389d59baaed0329da561c1',
    messagingSenderId: '345031892052',
    projectId: 'social-sphere-c2d28',
    storageBucket: 'social-sphere-c2d28.appspot.com',
    iosBundleId: 'com.example.socialSphere.RunnerTests',
  );
}
